
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/tmp/pip-build-env-d03x_cdu/overlay/lib/python3.12/site-packages/cmake/data/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/tmp/pip-build-env-d03x_cdu/overlay/bin/"
      - "/tmp/pip-build-env-d03x_cdu/normal/bin/"
      - "/common/home/ndb68/CG/.venv/bin/"
      - "/common/home/ndb68/.vscode-server/cli/servers/Stable-7d842fb85a0275a4a8e4d7e040d2625abbf7f084/server/bin/remote-cli/"
      - "/common/home/ndb68/.elan/bin/"
      - "/common/home/ndb68/.local/bin/"
      - "/common/home/ndb68/.cargo/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/snap/bin/"
      - "/common/home/ndb68/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/"
    searched_directories:
      - "/tmp/pip-build-env-d03x_cdu/overlay/bin/uname"
      - "/tmp/pip-build-env-d03x_cdu/normal/bin/uname"
      - "/common/home/ndb68/CG/.venv/bin/uname"
      - "/common/home/ndb68/.vscode-server/cli/servers/Stable-7d842fb85a0275a4a8e4d7e040d2625abbf7f084/server/bin/remote-cli/uname"
      - "/common/home/ndb68/.elan/bin/uname"
      - "/common/home/ndb68/.local/bin/uname"
      - "/common/home/ndb68/.cargo/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/tmp/pip-build-env-d03x_cdu/overlay/bin"
        - "/tmp/pip-build-env-d03x_cdu/normal/bin"
        - "/common/home/ndb68/CG/.venv/bin"
        - "/common/home/ndb68/.vscode-server/cli/servers/Stable-7d842fb85a0275a4a8e4d7e040d2625abbf7f084/server/bin/remote-cli"
        - "/common/home/ndb68/.elan/bin"
        - "/common/home/ndb68/.local/bin"
        - "/common/home/ndb68/.cargo/bin"
        - "/common/home/ndb68/.elan/bin"
        - "/common/home/ndb68/.local/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/snap/bin"
        - "/common/home/ndb68/.local/bin"
        - "/common/home/ndb68/.local/bin"
        - "/common/home/ndb68/.local/bin"
        - "/common/home/ndb68/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand"
        - "/common/home/ndb68/.local/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/tmp/pip-build-env-d03x_cdu/overlay/lib/python3.12/site-packages/cmake/data/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.8.0-85-generic - x86_64
...
